import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import '../models/product_table_model.dart';
import '../services/firebase_product_service.dart';

class ProductsView extends StatefulWidget {
  const ProductsView({super.key});

  @override
  State<ProductsView> createState() => _ProductsViewState();
}

class _ProductsViewState extends State<ProductsView> {
  final _searchCtrl = TextEditingController();
  String _searchQuery = '';

  @override
  void dispose() {
    _searchCtrl.dispose();
    super.dispose();
  }

  /// Helper to render product image regardless of format (base64 string, HTTP URL, or fallback)
  static Widget _buildProductImage(
    String imageStr, {
    double width = 44,
    double height = 44,
    BoxFit fit = BoxFit.cover,
    Color? brandColor,
  }) {
    final cleanStr = imageStr.trim();

    if (cleanStr.isEmpty) {
      return Container(
        width: width,
        height: height,
        color: Colors.grey.shade100,
        child: Icon(Icons.fastfood, color: brandColor ?? Colors.deepOrange, size: width * 0.45),
      );
    }

    if (cleanStr.contains('base64,')) {
      try {
        final base64Data = cleanStr.split('base64,').last;
        final bytes = base64Decode(base64Data);
        return Image.memory(
          bytes,
          width: width,
          height: height,
          fit: fit,
          errorBuilder: (ctx, err, stack) => Container(
            width: width,
            height: height,
            color: Colors.grey.shade100,
            child: Icon(Icons.broken_image, color: Colors.grey, size: width * 0.45),
          ),
        );
      } catch (_) {}
    }

    if (cleanStr.startsWith('http://') || cleanStr.startsWith('https://')) {
      return Image.network(
        cleanStr,
        width: width,
        height: height,
        fit: fit,
        errorBuilder: (ctx, err, stack) => Container(
          width: width,
          height: height,
          color: Colors.grey.shade100,
          child: Icon(Icons.broken_image, color: Colors.grey, size: width * 0.45),
        ),
      );
    }

    // Direct Base64 attempt
    try {
      final bytes = base64Decode(cleanStr);
      return Image.memory(
        bytes,
        width: width,
        height: height,
        fit: fit,
        errorBuilder: (ctx, err, stack) => Container(
          width: width,
          height: height,
          color: Colors.grey.shade100,
          child: Icon(Icons.fastfood, color: brandColor ?? Colors.deepOrange, size: width * 0.45),
        ),
      );
    } catch (_) {}

    return Container(
      width: width,
      height: height,
      color: Colors.grey.shade100,
      child: Icon(Icons.fastfood, color: brandColor ?? Colors.deepOrange, size: width * 0.45),
    );
  }

  void _showAddProductDialog(
    BuildContext context, [
    ProductTableModel? existingProduct,
  ]) {
    final isEditing = existingProduct != null;
    final idCtrl = TextEditingController(
      text: isEditing ? existingProduct.productId : 'Auto-generated by Firebase',
    );
    final typeCtrl = TextEditingController(
      text: isEditing ? existingProduct.productType : 'Filipino',
    );
    final quantityCtrl = TextEditingController(
      text: isEditing ? existingProduct.productQuantity.toString() : '50',
    );
    final priceCtrl = TextEditingController(
      text: isEditing
          ? existingProduct.productPrice.toStringAsFixed(2)
          : '150.00',
    );
    final imageCtrl = TextEditingController(
      text: isEditing ? existingProduct.productImage : '',
    );

    bool isSaving = false;

    showDialog(
      context: context,
      builder: (dialogCtx) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            final currentImage = imageCtrl.text.trim();

            Future<void> pickImageFromDevice() async {
              try {
                final ImagePicker picker = ImagePicker();
                final XFile? image = await picker.pickImage(
                  source: ImageSource.gallery,
                  maxWidth: 800,
                  maxHeight: 800,
                  imageQuality: 85,
                );
                if (image != null) {
                  final bytes = await image.readAsBytes();
                  final mimeType = image.mimeType ?? 'image/jpeg';
                  final base64String = 'data:$mimeType;base64,${base64Encode(bytes)}';
                  imageCtrl.text = base64String;
                  setDialogState(() {});
                }
              } catch (e) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text('Could not pick image: $e')),
                  );
                }
              }
            }

            return AlertDialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              title: Row(
                children: [
                  Icon(
                    isEditing ? Icons.edit_note : Icons.add_shopping_cart,
                    color: Theme.of(context).colorScheme.primary,
                  ),
                  const SizedBox(width: 8),
                  Text(
                    isEditing ? 'Edit Product' : 'Add New Product',
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              content: SingleChildScrollView(
                child: SizedBox(
                  width: 440,
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Product ID (Auto-generated from Firebase)
                      TextField(
                        controller: idCtrl,
                        enabled: false,
                        decoration: InputDecoration(
                          labelText: 'Product ID (product_id)',
                          helperText: isEditing
                              ? 'Existing Product ID'
                              : 'Auto-generated document ID from Firebase ✨',
                          border: const OutlineInputBorder(),
                          prefixIcon: const Icon(Icons.auto_awesome),
                          filled: true,
                          fillColor: Colors.grey.shade100,
                        ),
                      ),
                      const SizedBox(height: 14),

                      // Product Type
                      TextField(
                        controller: typeCtrl,
                        decoration: const InputDecoration(
                          labelText: 'Product Type / Category (product_type)',
                          border: OutlineInputBorder(),
                          prefixIcon: Icon(Icons.category),
                        ),
                      ),
                      const SizedBox(height: 14),

                      // Stock Quantity & Price
                      Row(
                        children: [
                          Expanded(
                            child: TextField(
                              controller: quantityCtrl,
                              keyboardType: TextInputType.number,
                              decoration: const InputDecoration(
                                labelText: 'Quantity (product_quantity)',
                                border: OutlineInputBorder(),
                                prefixIcon: Icon(Icons.inventory_2),
                              ),
                            ),
                          ),
                          const SizedBox(width: 10),
                          Expanded(
                            child: TextField(
                              controller: priceCtrl,
                              keyboardType: const TextInputType.numberWithOptions(
                                decimal: true,
                              ),
                              decoration: const InputDecoration(
                                labelText: 'Price ₱ (product_price)',
                                border: OutlineInputBorder(),
                                prefixIcon: Icon(Icons.payments),
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 18),

                      // Insert Picture Section Title
                      const Text(
                        'Product Picture (product_image):',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      const SizedBox(height: 8),

                      // Device Picture Picker Button
                      SizedBox(
                        width: double.infinity,
                        child: ElevatedButton.icon(
                          onPressed: pickImageFromDevice,
                          icon: const Icon(Icons.add_a_photo, size: 20),
                          label: Text(
                            currentImage.isEmpty
                                ? 'Insert Picture from Device 📷'
                                : 'Change Picture from Device 📷',
                            style: const TextStyle(fontWeight: FontWeight.bold),
                          ),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Theme.of(context).colorScheme.primary,
                            foregroundColor: Colors.white,
                            padding: const EdgeInsets.symmetric(vertical: 14),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(height: 10),

                      // Live Image Preview Container
                      Container(
                        height: 130,
                        width: double.infinity,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(
                            color: currentImage.isNotEmpty
                                ? Theme.of(context).colorScheme.primary
                                : Colors.grey.shade300,
                            width: currentImage.isNotEmpty ? 2 : 1,
                          ),
                          color: Colors.grey.shade50,
                        ),
                        child: currentImage.isNotEmpty
                            ? Stack(
                                children: [
                                  Positioned.fill(
                                    child: ClipRRect(
                                      borderRadius: BorderRadius.circular(10),
                                      child: _buildProductImage(
                                        currentImage,
                                        width: double.infinity,
                                        height: 130,
                                        fit: BoxFit.cover,
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    top: 8,
                                    right: 8,
                                    child: CircleAvatar(
                                      backgroundColor: Colors.black.withValues(alpha: 0.6),
                                      radius: 16,
                                      child: IconButton(
                                        icon: const Icon(Icons.close, size: 16, color: Colors.white),
                                        padding: EdgeInsets.zero,
                                        onPressed: () {
                                          imageCtrl.clear();
                                          setDialogState(() {});
                                        },
                                        tooltip: 'Remove picture',
                                      ),
                                    ),
                                  ),
                                ],
                              )
                            : InkWell(
                                onTap: pickImageFromDevice,
                                borderRadius: BorderRadius.circular(12),
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: const [
                                    Icon(
                                      Icons.cloud_upload_outlined,
                                      size: 38,
                                      color: Colors.grey,
                                    ),
                                    SizedBox(height: 6),
                                    Text(
                                      'Click to select photo from device',
                                      style: TextStyle(
                                        color: Colors.grey,
                                        fontSize: 13,
                                        fontWeight: FontWeight.w500,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                      ),
                      const SizedBox(height: 12),

                      // Advanced / Optional Image URL Input
                      ExpansionTile(
                        tilePadding: EdgeInsets.zero,
                        title: const Text(
                          'Or enter image URL / Preset pictures',
                          style: TextStyle(fontSize: 12, color: Colors.grey),
                        ),
                        children: [
                          TextField(
                            controller: imageCtrl,
                            onChanged: (_) => setDialogState(() {}),
                            decoration: const InputDecoration(
                              labelText: 'Picture URL (product_image)',
                              hintText: 'https://images.unsplash.com/...',
                              border: OutlineInputBorder(),
                              prefixIcon: Icon(Icons.link),
                            ),
                          ),
                          const SizedBox(height: 8),
                          Wrap(
                            spacing: 6,
                            runSpacing: 6,
                            children: [
                              _buildImagePresetChip('🍗 Inasal', 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=500', imageCtrl, setDialogState),
                              _buildImagePresetChip('🍲 Kare-Kare', 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500', imageCtrl, setDialogState),
                              _buildImagePresetChip('🥩 Adobo', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500', imageCtrl, setDialogState),
                              _buildImagePresetChip('🍧 Halo-Halo', 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=500', imageCtrl, setDialogState),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
              actions: [
                TextButton(
                  onPressed: isSaving ? null : () => Navigator.pop(dialogCtx),
                  child: const Text('Cancel'),
                ),
                ElevatedButton(
                  onPressed: isSaving
                      ? null
                      : () async {
                          final productType = typeCtrl.text.trim();
                          final quantity =
                              int.tryParse(quantityCtrl.text.trim()) ?? 0;
                          final price =
                              double.tryParse(priceCtrl.text.trim()) ?? 0.0;
                          final imageUrl = imageCtrl.text.trim();

                          if (productType.isEmpty) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text('Please enter Product Type'),
                              ),
                            );
                            return;
                          }

                          setDialogState(() => isSaving = true);

                          final newProduct = ProductTableModel(
                            productId: isEditing ? existingProduct.productId : '',
                            productQuantity: quantity,
                            productType: productType,
                            productPrice: price,
                            productImage: imageUrl,
                          );

                          final savedProduct =
                              await FirebaseProductService.saveProductToFirestore(
                                newProduct,
                              );

                          if (dialogCtx.mounted) {
                            Navigator.pop(dialogCtx);
                          }
                          if (context.mounted) {
                            ScaffoldMessenger.of(context).showSnackBar(
                              SnackBar(
                                content: Text(
                                  '${isEditing ? "Updated" : "Added"} ${savedProduct.productId} in product_table 🔥',
                                ),
                                backgroundColor: Colors.green,
                              ),
                            );
                          }
                        },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Theme.of(context).colorScheme.primary,
                    foregroundColor: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: isSaving
                      ? const SizedBox(
                          width: 18,
                          height: 18,
                          child: CircularProgressIndicator(
                            color: Colors.white,
                            strokeWidth: 2,
                          ),
                        )
                      : Text(isEditing ? 'Save Changes' : 'Add Product'),
                ),
              ],
            );
          },
        );
      },
    );
  }

  Widget _buildImagePresetChip(
    String label,
    String url,
    TextEditingController controller,
    StateSetter setDialogState,
  ) {
    return ActionChip(
      avatar: const Icon(Icons.photo_library, size: 14),
      label: Text(label, style: const TextStyle(fontSize: 11)),
      onPressed: () {
        controller.text = url;
        setDialogState(() {});
      },
    );
  }

  void _confirmDeleteProduct(BuildContext context, String productId) {
    showDialog(
      context: context,
      builder: (dialogCtx) => AlertDialog(
        title: const Text('Delete Product'),
        content: Text(
          'Are you sure you want to delete "$productId" from product_table?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(dialogCtx),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              await FirebaseProductService.deleteProductFromFirestore(
                productId,
              );
              if (context.mounted) {
                Navigator.pop(dialogCtx);
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text('Deleted $productId from product_table'),
                  ),
                );
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final brandColor = Theme.of(context).colorScheme.primary;

    return LayoutBuilder(
      builder: (context, constraints) {
        final isMobile = constraints.maxWidth < 650;
        final padding = isMobile ? 16.0 : 32.0;

        return SingleChildScrollView(
          padding: EdgeInsets.all(padding),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Wrap(
                alignment: WrapAlignment.spaceBetween,
                crossAxisAlignment: WrapCrossAlignment.center,
                runSpacing: 12,
                spacing: 16,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: const [
                      Text(
                        'Product Management',
                        style: TextStyle(
                          fontSize: 24,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                  ElevatedButton.icon(
                    onPressed: () => _showAddProductDialog(context),
                    icon: const Icon(Icons.add, size: 18),
                    label: const Text('Add Product'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: brandColor,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(
                        horizontal: 20,
                        vertical: 14,
                      ),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),
              // StreamBuilder for real-time Cloud Firestore updates
              StreamBuilder<List<ProductTableModel>>(
                stream: FirebaseProductService.streamProducts(),
                builder: (context, snapshot) {
                  if (snapshot.connectionState == ConnectionState.waiting &&
                      !snapshot.hasData) {
                    return const Center(
                      child: Padding(
                        padding: EdgeInsets.all(40),
                        child: CircularProgressIndicator(),
                      ),
                    );
                  }

                  final products = snapshot.data ?? [];
                  final filteredProducts = products.where((p) {
                    final query = _searchQuery.toLowerCase();
                    return p.productId.toLowerCase().contains(query) ||
                        p.productType.toLowerCase().contains(query) ||
                        p.productPrice.toString().contains(query);
                  }).toList();

                  if (filteredProducts.isEmpty) {
                    return Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(40),
                      decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: Column(
                        children: [
                          const Icon(
                            Icons.inventory_2_outlined,
                            size: 48,
                            color: Colors.grey,
                          ),
                          const SizedBox(height: 12),
                          const Text(
                            'No products found in product_table',
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 16,
                            ),
                          ),
                          const SizedBox(height: 8),
                          TextButton.icon(
                            onPressed: () => _showAddProductDialog(context),
                            icon: const Icon(Icons.add),
                            label: const Text('Add your first product'),
                          ),
                        ],
                      ),
                    );
                  }

                  return Container(
                    width: double.infinity,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withValues(alpha: 0.05),
                          blurRadius: 10,
                          offset: const Offset(0, 4),
                        ),
                      ],
                    ),
                    child: SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: ConstrainedBox(
                        constraints: BoxConstraints(
                          minWidth: (constraints.maxWidth - (padding * 2))
                              .clamp(700.0, double.infinity),
                        ),
                        child: DataTable(
                          columnSpacing: isMobile ? 16 : 28,
                          headingRowColor: WidgetStateProperty.all(
                            const Color(0xFFF8FAFC),
                          ),
                          columns: const [
                            DataColumn(
                              label: Text(
                                'Picture (product_image)',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            DataColumn(
                              label: Text(
                                'Product ID (product_id)',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            DataColumn(
                              label: Text(
                                'Category (product_type)',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            DataColumn(
                              label: Text(
                                'Price (product_price)',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            DataColumn(
                              label: Text(
                                'Stock (product_quantity)',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                            DataColumn(
                              label: Text(
                                'Actions',
                                style: TextStyle(fontWeight: FontWeight.bold),
                              ),
                            ),
                          ],
                          rows: filteredProducts.map((product) {
                            final isOutOfStock = product.productQuantity <= 0;

                            return DataRow(
                              cells: [
                                // Product Image Cell
                                DataCell(
                                  Container(
                                    width: 44,
                                    height: 44,
                                    decoration: BoxDecoration(
                                      color: Colors.grey.shade100,
                                      borderRadius: BorderRadius.circular(8),
                                      border: Border.all(
                                        color: Colors.grey.shade200,
                                      ),
                                    ),
                                    child: ClipRRect(
                                      borderRadius: BorderRadius.circular(8),
                                      child: _buildProductImage(
                                        product.productImage,
                                        width: 44,
                                        height: 44,
                                        fit: BoxFit.cover,
                                        brandColor: brandColor,
                                      ),
                                    ),
                                  ),
                                ),
                                // Product ID Cell
                                DataCell(
                                  Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Text(
                                        product.productId,
                                        style: const TextStyle(
                                          fontWeight: FontWeight.bold,
                                          fontSize: 13,
                                        ),
                                      ),
                                      Text(
                                        product.productType,
                                        style: const TextStyle(
                                          color: Colors.grey,
                                          fontSize: 11,
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                DataCell(
                                  Container(
                                    padding: const EdgeInsets.symmetric(
                                      horizontal: 10,
                                      vertical: 4,
                                    ),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFF1F5F9),
                                      borderRadius: BorderRadius.circular(12),
                                    ),
                                    child: Text(
                                      product.productType,
                                      style: const TextStyle(
                                        fontSize: 12,
                                        fontWeight: FontWeight.w500,
                                        color: Color(0xFF475569),
                                      ),
                                    ),
                                  ),
                                ),
                                DataCell(
                                  Text(
                                    '₱${product.productPrice.toStringAsFixed(2)}',
                                    style: const TextStyle(
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                                DataCell(
                                  Text(
                                    isOutOfStock
                                        ? 'Out of stock'
                                        : '${product.productQuantity} in stock',
                                    style: TextStyle(
                                      color: isOutOfStock
                                          ? Colors.red
                                          : Colors.green,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                                DataCell(
                                  Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      TextButton(
                                        onPressed: () => _showAddProductDialog(
                                          context,
                                          product,
                                        ),
                                        style: TextButton.styleFrom(
                                          foregroundColor: brandColor,
                                        ),
                                        child: const Text('Edit'),
                                      ),
                                      IconButton(
                                        onPressed: () => _confirmDeleteProduct(
                                          context,
                                          product.productId,
                                        ),
                                        icon: const Icon(
                                          Icons.delete_outline,
                                          size: 18,
                                          color: Colors.grey,
                                        ),
                                        tooltip: 'Delete',
                                      ),
                                    ],
                                  ),
                                ),
                              ],
                            );
                          }).toList(),
                        ),
                      ),
                    ),
                  );
                },
              ),
            ],
          ),
        );
      },
    );
  }
}
