import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/product_table_model.dart';
import 'firebase_order_service.dart';

/// FirebaseProductService manages Cloud Firestore real-time streaming,
/// fetching, creation, and updating of records in the `product_table` collection.
class FirebaseProductService {
  /// Live real-time stream of product_table items from Cloud Firestore & Laravel DB
  static Stream<List<ProductTableModel>> streamProducts({
    Duration interval = const Duration(seconds: 4),
  }) async* {
    while (true) {
      try {
        final products = await fetchProductsFromFirestore();
        yield products;
      } catch (_) {
        yield [];
      }
      await Future.delayed(interval);
    }
  }

  /// Fetch all documents from Cloud Firestore `product_table` collection & Laravel DB
  static Future<List<ProductTableModel>> fetchProductsFromFirestore() async {
    final projectId = FirebaseOrderService.firebaseProjectId;

    // 1. Fetch from Firebase Cloud Firestore
    if (projectId.isNotEmpty) {
      final url = Uri.parse(
        'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents/product_table',
      );

      try {
        final response = await http.get(url);
        if (response.statusCode == 200) {
          final Map<String, dynamic> data = json.decode(response.body);
          final List<dynamic> documents = data['documents'] ?? [];
          return documents
              .map((doc) => ProductTableModel.fromFirestore(doc))
              .toList();
        }
      } catch (_) {}
    }

    // 2. Fallback to Laravel REST API if Firebase returns empty or network error
    try {
      final laravelUrl = Uri.parse('http://127.0.0.1:8000/api/product-table');
      final response = await http.get(laravelUrl);
      if (response.statusCode == 200) {
        final List<dynamic> data = json.decode(response.body);
        return data.map((json) => ProductTableModel.fromJson(json)).toList();
      }
    } catch (_) {}

    return [];
  }

  /// Add or update a product in Firestore `product_table` collection & Laravel DB
  static Future<ProductTableModel> saveProductToFirestore(ProductTableModel product) async {
    final projectId = FirebaseOrderService.firebaseProjectId;
    String docId = product.productId.trim();
    final bool isNewProduct = docId.isEmpty || docId.startsWith('AUTO-') || docId == 'Auto-generated by Firebase';

    // 1. If Firebase is configured and adding a new product, POST to Firestore to let Firebase auto-generate ID
    if (projectId.isNotEmpty && isNewProduct) {
      final postUrl = Uri.parse(
        'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents/product_table',
      );

      try {
        final initialPayload = product.toFirestoreFields();
        final response = await http.post(
          postUrl,
          headers: {'Content-Type': 'application/json'},
          body: json.encode(initialPayload),
        );

        if (response.statusCode == 200) {
          final Map<String, dynamic> data = json.decode(response.body);
          final namePath = data['name']?.toString() ?? '';
          final generatedId = namePath.split('/').last;
          if (generatedId.isNotEmpty) {
            docId = 'PROD-FB-$generatedId';
          }
        }
      } catch (_) {}
    }

    if (docId.isEmpty || isNewProduct && !docId.startsWith('PROD-FB-')) {
      docId = 'PROD-FB-${DateTime.now().millisecondsSinceEpoch % 1000000}';
    }

    final finalProduct = ProductTableModel(
      productId: docId,
      productQuantity: product.productQuantity,
      productType: product.productType,
      productPrice: product.productPrice,
      productImage: product.productImage,
    );

    // 2. Sync to Laravel REST API if running
    try {
      final laravelUrl = Uri.parse('http://127.0.0.1:8000/api/product-table');
      await http.post(
        laravelUrl,
        headers: {'Content-Type': 'application/json'},
        body: json.encode(finalProduct.toJson()),
      );
    } catch (_) {}

    // 3. Patch Cloud Firestore REST API with finalized document ID
    if (projectId.isNotEmpty) {
      final patchUrl = Uri.parse(
        'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents/product_table/$docId',
      );

      try {
        await http.patch(
          patchUrl,
          headers: {'Content-Type': 'application/json'},
          body: json.encode(finalProduct.toFirestoreFields()),
        );
      } catch (_) {}
    }

    return finalProduct;
  }

  /// Delete a product document from Firestore `product_table` collection & Laravel DB
  static Future<bool> deleteProductFromFirestore(String productId) async {
    // 1. Delete from Laravel REST API if running
    try {
      final laravelUrl = Uri.parse('http://127.0.0.1:8000/api/product-table/$productId');
      await http.delete(laravelUrl);
    } catch (_) {}

    // 2. Delete from Cloud Firestore REST API
    final projectId = FirebaseOrderService.firebaseProjectId;
    if (projectId.isEmpty) return true;

    final url = Uri.parse(
      'https://firestore.googleapis.com/v1/projects/$projectId/databases/(default)/documents/product_table/$productId',
    );

    try {
      final response = await http.delete(url);
      return response.statusCode == 200;
    } catch (_) {
      return true;
    }
  }
}

