import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;
import '../models/product_table_model.dart';
import 'api_service.dart';

/// ProductTableService manages real-time streaming, fetching, creation,
/// updating, and deletion of records in `product_table` directly via Laravel SQLite.
class FirebaseProductService {
  /// Live real-time stream of product_table items from Laravel DB (polls every 4s)
  static Stream<List<ProductTableModel>> streamProducts({
    Duration interval = const Duration(seconds: 4),
  }) async* {
    while (true) {
      try {
        final products = await fetchProductsFromFirestore();
        yield products;
      } catch (_) {
        yield [];
      }
      await Future.delayed(interval);
    }
  }

  /// Fetch all products directly from Laravel REST API
  static Future<List<ProductTableModel>> fetchProductsFromFirestore() async {
    try {
      final laravelUrl = Uri.parse('${ApiService.baseUrl}/product-table');
      final response = await http.get(laravelUrl);
      if (response.statusCode == 200) {
        final List<dynamic> data = json.decode(response.body);
        return data.map((json) => ProductTableModel.fromJson(json)).toList();
      }
    } catch (_) {}

    return [];
  }

  /// Add or update a product in Laravel DB
  static Future<ProductTableModel> saveProductToFirestore(ProductTableModel product) async {
    String docId = product.productId.trim();
    if (docId.isEmpty || docId.startsWith('AUTO-') || docId == 'Auto-generated by Firebase') {
      docId = 'PROD-${DateTime.now().millisecondsSinceEpoch % 1000000}';
    }

    final finalProduct = ProductTableModel(
      productId: docId,
      productQuantity: product.productQuantity,
      productType: product.productType,
      productPrice: product.productPrice,
      productImage: product.productImage,
    );

    try {
      final laravelUrl = Uri.parse('${ApiService.baseUrl}/product-table');
      await http.post(
        laravelUrl,
        headers: {'Content-Type': 'application/json'},
        body: json.encode(finalProduct.toJson()),
      );
    } catch (_) {}

    return finalProduct;
  }

  /// Delete a product document from Laravel DB
  static Future<bool> deleteProductFromFirestore(String productId) async {
    try {
      final laravelUrl = Uri.parse('${ApiService.baseUrl}/product-table/$productId');
      final response = await http.delete(laravelUrl);
      return response.statusCode == 200;
    } catch (_) {
      return false;
    }
  }
}
